version: 0.0.1[{build}]

clone_depth: 1

branches:
  only:
    - master
    - dev

cache:
  - c:\usr

image: Visual Studio 2019

environment:
  matrix:
    - CMAKE_VS_VERSION: "16 2019"

platform:
  - x64
configuration:
  - Debug
  - Release

before_build:
  - git submodule -q update --init --recursive
  - cmake -DSTANDALONE=ON -DCMAKE_BUILD_TYPE=%configuration% -G "Visual Studio %CMAKE_VS_VERSION%"

build_script:
  - dir
  - msbuild CppDecoder.sln /m /p:Configuration=%configuration% /p:Platform=%platform% /t:ALL_BUILD

test_script:
  - cmd: ctest -C %configuration%
